export const answers = [
  "C'est certain.",
  "Sans aucun doute.",
  "Oui, absolument.",
  "Très probable.",
  "Oui, définitivement.",
  "Vous pouvez compter dessus.",
  "Il en est décidé ainsi.",
  "Il est certainement vrai.",
  "Oui, c'est sûr.",
  "Probablement.",
  "Les signes pointent vers oui.",
  "Réponse vague, essayez à nouveau.",
  "Mieux vaut ne pas vous le dire maintenant.",
  "Impossible à prédire pour le moment.",
  "Concentrez-vous et demandez à nouveau.",
  "Ne comptez pas dessus.",
  "Ma réponse est non.",
  "Mes sources disent non.",
  "Très peu probable.",
  "Non, définitivement.",
  "Non, oubliez ça.",
  "Je dirais que c'est peu probable.",
  "Les perspectives ne sont pas bonnes.",
  "Très incertain."
]